"""Pydantic models and DB helpers for onboarding plans."""

from __future__ import annotations

import json
import logging
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field
from sqlalchemy import text

from api.db.session import get_engine

logger = logging.getLogger(__name__)


class KeyFile(BaseModel):
    """A key file relevant to the user's focus area."""

    path: str = Field(description="Relative file path in the repo")
    why: str = Field(description="Why this file matters for the focus area")


class OnboardingStep(BaseModel):
    """A single guided step in the onboarding plan."""

    title: str = Field(description="Step title")
    description: str = Field(description="What to do in this step")
    files: list[str] = Field(default_factory=list, description="Relevant file paths")


class OnboardingPlan(BaseModel):
    """Full onboarding plan generated by the AI agent."""

    summary: str = Field(description="High-level repo summary tailored to focus")
    architecture: str = Field(description="Architecture overview from the focus perspective")
    setup: str = Field(description="Setup instructions for getting started")
    key_files: list[KeyFile] = Field(default_factory=list, description="Key files for this focus")
    steps: list[OnboardingStep] = Field(default_factory=list, description="Guided walkthrough steps")


async def upsert_onboarding_plan(repo_id: str, plan_dict: dict[str, Any]) -> bool:
    """Save or update an onboarding plan in the database. Returns True on success."""
    engine = get_engine()
    if engine is None:
        logger.warning("DB engine not initialized — skipping onboarding plan upsert")
        return False

    try:
        async with engine.connect() as conn:
            await conn.execute(
                text("""
                    INSERT INTO repo_onboarding_plans (repo_id, plan, updated_at)
                    VALUES (CAST(:repo_id AS uuid), CAST(:plan AS jsonb), NOW())
                    ON CONFLICT (repo_id)
                    DO UPDATE SET plan = CAST(EXCLUDED.plan AS jsonb), updated_at = NOW()
                """),
                {"repo_id": repo_id, "plan": json.dumps(plan_dict)},
            )
            await conn.commit()
        return True
    except Exception as exc:
        logger.error(f"Failed to upsert onboarding plan for {repo_id}: {exc}")
        return False
